### ISSUE TITLE
Should Assembly Press refer to the protocol as a whole while AssemblyPress refers directly to the factory contract?

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/AssemblyPress#17]
Is it confusing to have both the protocol and factory named AssemblyPress? This is something I started thinking about while beginning to write the walkthrough.

Also, side note. I think that we should have the todos/remaining questions take the form of issues rather than inside the readme. Just leaves more flexibility to resolve things independently and even tag related parties if necessary.

**Comment by 0xTranqui** [comment]
totally agree about coming up with a new name for the factory for the reasons you stated. initial thought is it could be PressFactory? or PressCreator? do we want to add in a V1 like the ZoraNFTCreatorV1 has even tho it also relies on versions? fan of it just being called "PressX" because then it will make sense that u can deploy ERC721Press or ERC1155Press from it overtime

to ur second point yea -- issues obviously what these should be thx for splitting em out

**Comment by salieflewis** [comment]
Both of those feel like the obvious choices in terms of clarity, although they do sound quite stale. But it is also not a really big deal cause the magic doesn't live in the factories.

I feel like you started introducing the V1 thing with the storage contract, so if it makes sense here for consistency I am game.

Or is that only because the storage contract doesn't include an external versioning system?

**Comment by salieflewis** [comment]
Went with PressFactory, which inherits from the Version utility
