### ISSUE TITLE
Implement promoteToEdition functionality inside ERC721Press

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/AssemblyPress#19]
Need to articulate what exactly promoteToEdition will accomplish and with what parameters. Same for createEdition, and deciding to include these functions or not.

**Comment by 0xTranqui** [comment]
defining these other wise kind of amorphous architectures will be really important. bc it will be key that ppl can pass in their own logic files with wtv arbitrary access control checks they want, while still using the ArtifactRenderer unilaterally (so that front end packages can be built around ArtifactRenderer and be cross compatible regardless of Logic impl)

**Comment by salieflewis** [comment]
<img width="775" alt="CleanShot 2023-01-08 at 20 32 05@2x" src="https://user-images.githubusercontent.com/37086973/211229049-6b5cf925-00ff-4134-9619-d8b918d27d0b.png">
